### ISSUE TITLE
Return user search results in a table

### ISSUE THREAD

**Issue by liminal-dog** [DiamondDAO/chainverse-os#1]
**Summary**
- A user should be able to submit a natural language search and view a table with results.

**Requirements**
- Search should span across the following object types: (i) Entity, (ii) Block, (ii) Tag, (iv) Proposal
- Search results should resolve to entities. For instance, if a user searches `knowledge graph` we might see hits on multiple blocks and tags. Instead of returning blocks/tags, we should return the *entities* those blocks and tags are connected to.
- Each search result should include relevant metadata: (i) how many blocks are associated with the entity, (ii) how many tags are associated with the entity, (iii) an icon user can click to open up a workspace displaying the entity's `Profile` (more details in `Entity Profile`)
- User should be able to filter and sort results
    - Filtering: (i) existence of value in user-selected results column, (ii) tags associated with entities
    - Sorting: in ascending / descending order for result columns with numerical values

**Wireframes** 
- https://balsamiq.cloud/s3mfqq9/pwwthkq (first two slides)

**Comment by clemp** [comment]
Example queries to set up Neo4j full text search

```cypher
CREATE FULLTEXT INDEX titlesAndDescriptions FOR (n:Movie|Book) ON EACH [n.title, n.description]

CALL db.index.fulltext.queryNodes("context", $neodash_query) YIELD node
unwind(node) as signal
match (c:Contributor)-[r]-(signal:Signal)-[r1]-(t:Thread)
match (ch:Channel)-[r2]-(t)
return c,r,signal,r1,t,ch,r2
limit 75
```

**Comment by clemp** [comment]
Based on feedback during conversation with @liminal-dog yesterday I made updates to the search query and results.

**Returning `Entity` nodes only**

- The search results will only include `Entity` nodes (instead of `Note`, `Partnership`, etc like we originally started with)
- Table of search results will display 4 columns for now: `Name`, `# of Notes relations`, `# of Proposals relations`, `View more`
    - Eventually I want this to change to `Total # of Relations` but that's more complicated to implement with GraphQL so we can save for a future iteration

**Path Expander Search**
- I modified the `fuzzyChainversePortalSearch` function to have two steps:
    - Match text in `Notes`, `Proposals`, or `Entity` nodes that contain the search string that was entered
    - Pass the matched node to Neo4j [Path Expander function](https://neo4j.com/labs/apoc/4.3/graph-querying/expand-subgraph-nodes/) to return the `Entity` with a `REFERENCES` or `HAS_PROPOSAL` relation between the matched node and that `Entity`

**Modified GraphQL Type Definition**

```graphql
union SearchNodes = Note | Entity | Proposal

  type Query {
    fuzzyChainversePortalSearch(searchString: String, skip: Int, limit: Int): [SearchNodes] @cypher(
      statement: """
        CALL db.index.fulltext.queryNodes(
          'chainversePortalSearchIndex', $searchString+'~')
        YIELD node as searchResult, score 
        WHERE score > 0.9
        WITH searchResult
        CALL apoc.path.subgraphNodes(searchResult, {
          relationshipFilter: 'REFERENCES|HAS_PROPOSAL',
          labelFilter: '>Entity',
            minLevel: 1,
            maxLevel: 2
        })
        YIELD node as r
        RETURN r
        SKIP $skip LIMIT $limit
      """
    )
  }
```

**Search Result Sample**

Now this query

```graphql
query FuzzyChainversePortalSearch($searchString: String, $skip: Int, $limit: Int) {
  fuzzyChainversePortalSearch(searchString: $searchString, skip: $skip, limit: $limit) {
    ... on Entity {
      uuid
      name
      notesAggregate {
        count
      }
      proposalsAggregate {
        count
      }
    }
  }
}
```

with this variable input

```graphql
{
  "searchString": "investor",
  "skip": 0,
  "limit": 10
}
```

Produces a JSON structure like this 

```json
{
  "data": {
    "fuzzyChainversePortalSearch": [
      {
        "uuid": "1dfe665e-1e2e-4be7-8fb9-430bd36e40e0",
        "name": "Actor DAO",
        "notesAggregate": {
          "count": 0
        },
        "proposalsAggregate": {
          "count": 61
        }
      },
      {
        "uuid": "44126fbf-840f-44dc-80c5-c8d3755fb80f",
        "name": "PancakeSwap",
        "notesAggregate": {
          "count": 0
        },
        "proposalsAggregate": {
          "count": 587
        }
      },
      {
        "uuid": "dd4b09ef-cb03-4fec-add0-2b7ee247bd0c",
        "name": "CafeSwap.Finance",
        "notesAggregate": {
          "count": 0
        },
        "proposalsAggregate": {
          "count": 21
        }
      },

```

**Notes**

- We still don't have a count of the total number of results returned. We'll work on implementing that later (not sure how to accomplish it with the pagination).
- The `View More` link will reference the `Entity.uuid` property to bring up more information about that `Entity`

**Comment by liminal-dog** [comment]
We have a similar issue in `Chainverse Portal` should we close this ticket?
