### ISSUE TITLE
`Search` component configuration needs to include database endpoint configuration

### ISSUE THREAD

**Issue by clemp** [DiamondDAO/chainverse-os#4]
Currently the endpoint used for the `Search` component is still using the endpoint for the `chainverse-frontend` application that's deployed. 

This works for our current deployment of the application on `staging.chainverse.diamonds`, but does not work if another user wants to build their own Chainverse application, import the `Search` component, and connect to their own database.

@jose-zamora and I discussed creating a React [hook](https://github.com/DiamondDAO/chainverse-os/tree/main/src/hooks) within this `chainverse-os` package to include a way for developers to point `Search` to a specific endpoint.

I'm not 100% sure the best design to implement this enhancement; the hook idea was one that @jose-zamora brainstormed. Before committing to this Issue we can use comments here to decide on the design.

**Comment by liminal-dog** [comment]
Should we close this ticket?

**Comment by liminal-dog** [comment]
we moved this to chainverse-portal
